/* ============================================================
   DICCIONARIO INTERACTIVO DE COMANDOS (comandos.js)
   Fichas de referencia rápida extraídas del material de
   "hacking_material":
     - comandos.pdf  (cheat sheet de comandos Linux)
     - Manual de Linux Bash.pdf
     - LINUX-FOR-HACKERS... (herramientas de Kali / pentesting)
   Cada ficha:
     { id, nombre, cat, fuente, sintaxis, desc, opciones[],
       ejemplos:[{c, n}], caso, aviso }
   ============================================================ */

const CATEGORIAS_CMD = ["Archivos", "Texto", "Usuarios", "Sistema", "Redes", "Bash", "Hacking"];

const COMANDOS = [
  /* ---------------- ARCHIVOS Y DIRECTORIOS (comandos.pdf) ---------------- */
  { id: "ls", nombre: "ls", cat: "Archivos", fuente: "comandos.pdf",
    sintaxis: "ls [opciones] [ruta]",
    desc: "Lista el contenido de un directorio. Sin ruta, muestra la carpeta actual.",
    opciones: ["-l : formato detallado (permisos, dueño, tamaño)", "-a : incluye archivos ocultos", "-R : recursivo (subcarpetas)", "-lh : tamaños legibles (KB, MB, GB)"],
    ejemplos: [{ c: "ls -la", n: "todo el contenido, incluidos ocultos, con detalle" }, { c: "ls -lh /var/log", n: "logs del sistema con tamaños legibles" }],
    caso: "Primer comando al entrar a un servidor: ver qué hay y con qué permisos antes de tocar nada.", aviso: "" },
  { id: "pwd", nombre: "pwd", cat: "Archivos", fuente: "comandos.pdf",
    sintaxis: "pwd [-L|-P]",
    desc: "Muestra la ruta absoluta del directorio en el que te encuentras.",
    opciones: ["-P : ruta física real (resuelve enlaces simbólicos)"],
    ejemplos: [{ c: "pwd", n: "ej: /home/santi/proyectos" }],
    caso: "Orientarte en scripts y sesiones SSH para no ejecutar comandos en la carpeta equivocada.", aviso: "" },
  { id: "cd", nombre: "cd", cat: "Archivos", fuente: "comandos.pdf",
    sintaxis: "cd [ruta]",
    desc: "Cambia de directorio. Sin argumentos te lleva a tu carpeta personal.",
    opciones: ["cd .. : sube un nivel", "cd - : vuelve al directorio anterior", "cd ~ : tu carpeta personal"],
    ejemplos: [{ c: "cd /etc/ssh", n: "ir a la config de SSH" }, { c: "cd -", n: "volver de un salto al directorio previo" }],
    caso: "Navegar rápido por el árbol de un servidor durante una auditoría o despliegue.", aviso: "" },
  { id: "mkdir", nombre: "mkdir", cat: "Archivos", fuente: "comandos.pdf",
    sintaxis: "mkdir [opciones] nombre",
    desc: "Crea uno o varios directorios.",
    opciones: ["-p : crea carpetas intermedias que falten", "-m : fija permisos al crear", "-v : informa de cada carpeta creada"],
    ejemplos: [{ c: "mkdir -p proyecto/src/utils", n: "crea toda la ruta de una vez" }],
    caso: "Preparar la estructura de un proyecto o de carpetas de evidencias en un pentest.", aviso: "" },
  { id: "rm", nombre: "rm", cat: "Archivos", fuente: "comandos.pdf",
    sintaxis: "rm [opciones] archivo...",
    desc: "Elimina archivos y directorios de forma permanente (no hay papelera).",
    opciones: ["-i : pide confirmación", "-r : recursivo (carpetas)", "-f : fuerza sin preguntar"],
    ejemplos: [{ c: "rm -i nota.txt", n: "borra pidiendo confirmación" }, { c: "rm -r carpeta_temp", n: "borra una carpeta y su contenido" }],
    caso: "Limpiar archivos temporales de una prueba.", aviso: "¡PELIGRO! 'rm -rf' borra sin retorno. Revisa SIEMPRE la ruta; nunca lo ejecutes con sudo a ciegas." },
  { id: "cp", nombre: "cp", cat: "Archivos", fuente: "comandos.pdf",
    sintaxis: "cp [opciones] origen destino",
    desc: "Copia archivos o directorios.",
    opciones: ["-r / -R : copia carpetas con su contenido", "-i : pregunta antes de sobrescribir", "-v : muestra lo que copia"],
    ejemplos: [{ c: "cp informe.txt ~/Documentos/", n: "copia a otra carpeta" }, { c: "cp -r web/ web_backup/", n: "duplica un sitio entero" }],
    caso: "Hacer una copia de seguridad de un archivo de configuración antes de modificarlo.", aviso: "" },
  { id: "mv", nombre: "mv", cat: "Archivos", fuente: "comandos.pdf",
    sintaxis: "mv origen destino",
    desc: "Mueve o renombra archivos y directorios.",
    opciones: ["-i : confirma antes de sobrescribir", "-v : modo detallado"],
    ejemplos: [{ c: "mv viejo.txt nuevo.txt", n: "renombrar" }, { c: "mv *.log /var/logs/", n: "mover todos los .log" }],
    caso: "Reorganizar logs o renombrar evidencias con un esquema claro.", aviso: "" },
  { id: "touch", nombre: "touch", cat: "Archivos", fuente: "comandos.pdf",
    sintaxis: "touch archivo",
    desc: "Crea un archivo vacío o actualiza su marca de tiempo.",
    opciones: ["-t : fija una fecha/hora concreta"],
    ejemplos: [{ c: "touch notas.md", n: "crea un archivo vacío" }],
    caso: "Generar rápidamente archivos de prueba o marcadores en scripts.", aviso: "" },
  { id: "find", nombre: "find", cat: "Archivos", fuente: "comandos.pdf",
    sintaxis: "find [ruta] [expresión]",
    desc: "Busca archivos y carpetas por nombre, tipo, tamaño, fecha o permisos.",
    opciones: ["-name : por nombre", "-type d|f : carpeta o archivo", "-perm : por permisos", "-mtime : por fecha de modificación"],
    ejemplos: [{ c: "find / -name '*.conf' 2>/dev/null", n: "todos los .conf del sistema" }, { c: "find . -perm -4000 2>/dev/null", n: "busca binarios SUID (interés en auditorías)" }],
    caso: "En un pentest, localizar archivos con permisos peligrosos (SUID) o credenciales olvidadas.", aviso: "" },
  { id: "tar", nombre: "tar", cat: "Archivos", fuente: "comandos.pdf",
    sintaxis: "tar [opciones] archivo.tar objetivo",
    desc: "Empaqueta varios archivos en un .tar, con compresión opcional.",
    opciones: ["-c : crear", "-x : extraer", "-z : comprimir con gzip", "-v : detallado", "-f : nombre de archivo"],
    ejemplos: [{ c: "tar -czf backup.tar.gz ~/Documentos", n: "comprime una carpeta" }, { c: "tar -xzf backup.tar.gz", n: "extrae" }],
    caso: "Empaquetar evidencias o hacer copias de seguridad antes de un cambio.", aviso: "" },
  { id: "chmod", nombre: "chmod", cat: "Usuarios", fuente: "comandos.pdf",
    sintaxis: "chmod [permisos] archivo",
    desc: "Modifica permisos de lectura (r=4), escritura (w=2) y ejecución (x=1) por dueño, grupo y otros.",
    opciones: ["+x : añade ejecución", "755 : rwx r-x r-x", "644 : rw- r-- r--", "-R : recursivo"],
    ejemplos: [{ c: "chmod +x script.sh", n: "hace ejecutable un script" }, { c: "chmod 600 id_rsa", n: "protege una clave privada" }],
    caso: "Asegurar claves SSH (600) o permitir la ejecución de tus scripts de automatización.", aviso: "Evita chmod 777: da control total a cualquiera y es un fallo de seguridad clásico." },
  { id: "chown", nombre: "chown", cat: "Usuarios", fuente: "comandos.pdf",
    sintaxis: "chown [opciones] dueño[:grupo] archivo",
    desc: "Cambia el propietario y/o grupo de un archivo o carpeta.",
    opciones: ["-R : recursivo", ":grupo : cambia también el grupo"],
    ejemplos: [{ c: "sudo chown www-data:www-data /var/www -R", n: "asigna el sitio web al usuario del servidor" }],
    caso: "Corregir permisos tras desplegar una aplicación web en un servidor.", aviso: "" }
];

/* ---------------- PROCESAMIENTO DE TEXTO (comandos.pdf) ---------------- */
COMANDOS.push(
  { id: "cat", nombre: "cat", cat: "Texto", fuente: "comandos.pdf",
    sintaxis: "cat archivo...",
    desc: "Muestra, combina y crea contenido de archivos por la salida estándar.",
    opciones: ["cat > f.txt : crea un archivo", "cat a b > c : combina archivos", "-n : numera líneas"],
    ejemplos: [{ c: "cat /etc/passwd", n: "ver usuarios del sistema" }, { c: "cat a.txt b.txt > todo.txt", n: "unir archivos" }],
    caso: "Inspeccionar rápido archivos de configuración o de credenciales durante una auditoría.", aviso: "" },
  { id: "grep", nombre: "grep", cat: "Texto", fuente: "comandos.pdf",
    sintaxis: "grep [opciones] patrón archivo",
    desc: "Busca líneas que contengan un patrón (texto o expresión regular). Esencial para filtrar logs.",
    opciones: ["-i : ignora mayúsculas", "-r : recursivo en carpetas", "-n : muestra número de línea", "-v : invierte (lo que NO coincide)"],
    ejemplos: [{ c: "grep -i error /var/log/syslog", n: "errores en el log del sistema" }, { c: "grep -rn 'password' .", n: "buscar credenciales en código" }],
    caso: "Analista SOC: filtrar millones de líneas de log para encontrar intentos de acceso o errores.", aviso: "" },
  { id: "sed", nombre: "sed", cat: "Texto", fuente: "comandos.pdf",
    sintaxis: "sed [opciones] 'script' archivo",
    desc: "Editor de flujo: busca, reemplaza o borra patrones sin abrir un editor.",
    opciones: ["s/a/b/ : sustituye a por b", "s/a/b/g : todas las coincidencias", "-i : edita el archivo in situ", "d : borra líneas"],
    ejemplos: [{ c: "sed 's/rojo/azul/g' colores.txt", n: "reemplaza todas las apariciones" }, { c: "sed -i 's/DEBUG/INFO/' app.conf", n: "edita el archivo directamente" }],
    caso: "Automatizar cambios de configuración en muchos servidores con un solo comando.", aviso: "Con -i modifica el archivo real; haz una copia antes." },
  { id: "awk", nombre: "awk", cat: "Texto", fuente: "comandos.pdf",
    sintaxis: "awk '/patrón/{acción}' archivo",
    desc: "Procesa texto por columnas: extrae y manipula campos ($1, $2...).",
    opciones: ["-F : define el separador de campos", "{print $1} : imprime la primera columna"],
    ejemplos: [{ c: "awk -F':' '{print $1}' /etc/passwd", n: "lista solo los nombres de usuario" }, { c: "ps aux | awk '{print $2, $11}'", n: "PID y comando de cada proceso" }],
    caso: "Generar informes a partir de logs o salidas de comandos en el día a día de un admin.", aviso: "" },
  { id: "head", nombre: "head / tail", cat: "Texto", fuente: "comandos.pdf",
    sintaxis: "head [-n N] archivo | tail [-n N|-f] archivo",
    desc: "head muestra las primeras líneas; tail las últimas. tail -f sigue un archivo en vivo.",
    opciones: ["-n N : número de líneas", "-f : (tail) seguimiento en tiempo real"],
    ejemplos: [{ c: "tail -f /var/log/auth.log", n: "vigilar accesos en tiempo real" }, { c: "head -n 20 datos.csv", n: "vistazo a las primeras filas" }],
    caso: "Monitoreo en vivo de logs de seguridad (auth.log) para detectar fuerza bruta.", aviso: "" },
  { id: "sort", nombre: "sort / cut", cat: "Texto", fuente: "comandos.pdf",
    sintaxis: "sort [opciones] archivo | cut [opciones] archivo",
    desc: "sort ordena líneas; cut extrae columnas/secciones de cada línea.",
    opciones: ["sort -n : numérico", "sort -r : descendente", "cut -d',' -f1 : campo 1 separado por coma"],
    ejemplos: [{ c: "cut -d',' -f3-5 lista.csv", n: "columnas 3 a 5 de un CSV" }, { c: "sort -rn numeros.txt", n: "ordena de mayor a menor" }],
    caso: "Preparar y limpiar datos extraídos antes de incluirlos en un reporte.", aviso: "" },
  { id: "nano", nombre: "nano", cat: "Texto", fuente: "Manual de Linux Bash.pdf",
    sintaxis: "nano archivo",
    desc: "Editor de texto en terminal, simple y directo, ideal para editar configuraciones.",
    opciones: ["Ctrl+O : guardar", "Ctrl+X : salir", "Ctrl+W : buscar"],
    ejemplos: [{ c: "sudo nano /etc/ssh/sshd_config", n: "editar la config de SSH" }],
    caso: "Editar archivos de configuración en servidores sin entorno gráfico.", aviso: "" }
);

/* ---------------- USUARIOS Y PERMISOS (comandos.pdf) ---------------- */
COMANDOS.push(
  { id: "sudo", nombre: "sudo", cat: "Usuarios", fuente: "comandos.pdf",
    sintaxis: "sudo comando",
    desc: "Ejecuta un comando con privilegios de administrador (root).",
    opciones: ["-i : abre shell de root", "-u usuario : ejecuta como otro usuario", "-l : lista permisos sudo"],
    ejemplos: [{ c: "sudo apt update", n: "tarea de administración" }, { c: "sudo -l", n: "ver qué puedo ejecutar como admin (clave en pentest)" }],
    caso: "En post-explotación (lab), 'sudo -l' revela vías de escalada de privilegios mal configuradas.", aviso: "Un comando con sudo puede romper el sistema. Úsalo solo cuando lo entiendas." },
  { id: "su", nombre: "su", cat: "Usuarios", fuente: "comandos.pdf",
    sintaxis: "su [opciones] [usuario]",
    desc: "Cambia de usuario en la shell actual; sin argumentos intenta pasar a root.",
    opciones: ["-l : carga el entorno de login del usuario", "-s : especifica otra shell"],
    ejemplos: [{ c: "su - santi", n: "cambiar al usuario santi con su entorno" }],
    caso: "Moverte entre cuentas durante administración o pruebas en laboratorio.", aviso: "" },
  { id: "useradd", nombre: "useradd / passwd", cat: "Usuarios", fuente: "comandos.pdf",
    sintaxis: "useradd usuario ; passwd usuario",
    desc: "Crea cuentas de usuario y gestiona sus contraseñas.",
    opciones: ["-m : crea su carpeta personal", "-G grupo : añade a grupos"],
    ejemplos: [{ c: "sudo useradd -m ana && sudo passwd ana", n: "crear usuario con su /home y contraseña" }],
    caso: "Altas de usuarios y políticas de acceso en administración de sistemas.", aviso: "" },
  { id: "whoami", nombre: "whoami / id", cat: "Usuarios", fuente: "comandos.pdf",
    sintaxis: "whoami | id",
    desc: "whoami muestra tu usuario actual; id muestra UID, GID y grupos.",
    opciones: [],
    ejemplos: [{ c: "id", n: "comprobar grupos (ej: si estás en 'sudo' o 'docker')" }],
    caso: "Tras obtener acceso en un lab, lo primero es saber 'quién soy y qué grupos tengo'.", aviso: "" }
);

/* ---------------- SISTEMA (comandos.pdf) ---------------- */
COMANDOS.push(
  { id: "ps", nombre: "ps", cat: "Sistema", fuente: "comandos.pdf / Linux for Hackers",
    sintaxis: "ps [opciones]",
    desc: "Muestra una instantánea de los procesos en ejecución (PID, usuario, comando).",
    opciones: ["aux : todos los procesos con detalle", "-ef : formato completo"],
    ejemplos: [{ c: "ps aux | grep ssh", n: "ver procesos de SSH" }, { c: "ps aux --sort=-%mem | head", n: "los que más memoria consumen" }],
    caso: "Como hacker/defensor: identificar qué software corre en segundo plano (antivirus, servicios).", aviso: "" },
  { id: "top", nombre: "top / htop", cat: "Sistema", fuente: "comandos.pdf",
    sintaxis: "top | htop",
    desc: "Monitor de procesos y recursos en tiempo real. htop es la versión interactiva y visual.",
    opciones: ["htop F9 : matar proceso", "htop F4 : filtrar"],
    ejemplos: [{ c: "htop", n: "monitor visual (instalar: sudo apt install htop)" }],
    caso: "Detectar un proceso que dispara la CPU (posible minero/malware) en un servidor.", aviso: "" },
  { id: "kill", nombre: "kill", cat: "Sistema", fuente: "comandos.pdf",
    sintaxis: "kill [señal] PID",
    desc: "Termina un proceso por su PID. SIGTERM (suave) por defecto; SIGKILL (-9) forzado.",
    opciones: ["-15 (TERM) : cierre ordenado", "-9 (KILL) : cierre forzado"],
    ejemplos: [{ c: "kill 4521", n: "cierre ordenado" }, { c: "kill -9 4521", n: "forzar cierre si no responde" }],
    caso: "Detener un servicio colgado o un proceso sospechoso durante una respuesta a incidentes.", aviso: "kill -9 no deja guardar datos; úsalo solo si el cierre normal falla." },
  { id: "systemctl", nombre: "systemctl", cat: "Sistema", fuente: "comandos.pdf",
    sintaxis: "systemctl [acción] servicio",
    desc: "Gestiona servicios del sistema (systemd): iniciar, parar, habilitar y consultar estado.",
    opciones: ["status / start / stop / restart", "enable : arranca al inicio", "disable : no arranca al inicio"],
    ejemplos: [{ c: "systemctl status ssh", n: "estado del servicio SSH" }, { c: "sudo systemctl enable --now ufw", n: "activa el firewall y lo deja permanente" }],
    caso: "Endurecer un servidor: desactivar servicios innecesarios reduce la superficie de ataque.", aviso: "" },
  { id: "df", nombre: "df / du", cat: "Sistema", fuente: "comandos.pdf",
    sintaxis: "df -h | du -sh ruta",
    desc: "df: espacio libre por disco. du: tamaño que ocupa un archivo o carpeta.",
    opciones: ["df -h : tamaños legibles", "du -sh : total de una carpeta"],
    ejemplos: [{ c: "df -h", n: "espacio libre de todos los discos" }, { c: "du -sh /var/log", n: "cuánto ocupan los logs" }],
    caso: "Diagnosticar un servidor que se quedó sin espacio (logs desbordados, por ejemplo).", aviso: "" },
  { id: "history", nombre: "history", cat: "Sistema", fuente: "comandos.pdf",
    sintaxis: "history",
    desc: "Lista los comandos ejecutados anteriormente en la shell.",
    opciones: ["!N : repite el comando número N", "Ctrl+R : búsqueda interactiva"],
    ejemplos: [{ c: "history | grep ssh", n: "recordar un comando ssh usado antes" }],
    caso: "En análisis forense, ~/.bash_history revela qué hizo un usuario o un atacante.", aviso: "" },
  { id: "man", nombre: "man", cat: "Sistema", fuente: "comandos.pdf",
    sintaxis: "man comando",
    desc: "Muestra el manual oficial de un comando: opciones, sintaxis y ejemplos.",
    opciones: ["/palabra : buscar dentro del manual", "q : salir"],
    ejemplos: [{ c: "man nmap", n: "manual completo de nmap" }],
    caso: "Tu mejor aliado: ante cualquier comando nuevo, 'man' es la fuente de verdad.", aviso: "" }
);

/* ---------------- REDES (comandos.pdf) ---------------- */
COMANDOS.push(
  { id: "ping", nombre: "ping", cat: "Redes", fuente: "comandos.pdf",
    sintaxis: "ping [opciones] host",
    desc: "Comprueba si un host es alcanzable y mide el tiempo de respuesta.",
    opciones: ["-c N : envía solo N paquetes", "-i : intervalo entre paquetes"],
    ejemplos: [{ c: "ping -c 4 8.8.8.8", n: "4 paquetes al DNS de Google" }],
    caso: "Diagnóstico básico: distinguir un fallo de red de un fallo de DNS (ping a IP vs dominio).", aviso: "" },
  { id: "ip", nombre: "ip / ifconfig", cat: "Redes", fuente: "comandos.pdf",
    sintaxis: "ip a | ip route",
    desc: "Muestra y configura interfaces de red e IPs. 'ip' reemplaza al antiguo 'ifconfig'.",
    opciones: ["ip a : interfaces e IPs", "ip route : tabla de rutas (puerta de enlace)"],
    ejemplos: [{ c: "ip a", n: "ver tu IP y tus interfaces" }, { c: "ip route", n: "ver la puerta de enlace" }],
    caso: "Conocer tu IP y red antes de un escaneo autorizado en tu propio laboratorio.", aviso: "" },
  { id: "netstat", nombre: "netstat / ss", cat: "Redes", fuente: "comandos.pdf / Linux for Hackers",
    sintaxis: "ss -tuln | netstat -tulnp",
    desc: "Muestra conexiones de red, puertos en escucha y sockets. 'ss' es el reemplazo moderno de netstat.",
    opciones: ["-t : TCP", "-u : UDP", "-l : en escucha", "-n : sin resolver nombres", "-p : proceso asociado"],
    ejemplos: [{ c: "ss -tuln", n: "qué puertos están abiertos en mi equipo" }, { c: "sudo ss -tulnp", n: "puertos y qué programa los usa" }],
    caso: "Auditar tu propio servidor: cerrar puertos/servicios que no deberían estar expuestos.", aviso: "" },
  { id: "traceroute", nombre: "traceroute", cat: "Redes", fuente: "comandos.pdf",
    sintaxis: "traceroute destino",
    desc: "Muestra el camino (saltos/routers) que recorren los paquetes hasta un destino.",
    opciones: ["-n : no resuelve nombres (más rápido)", "-m : máximo de saltos"],
    ejemplos: [{ c: "traceroute -n google.com", n: "ruta hasta Google sin resolver nombres" }],
    caso: "Diagnosticar dónde se corta o se ralentiza una conexión hacia un servicio.", aviso: "" },
  { id: "dig", nombre: "dig / nslookup", cat: "Redes", fuente: "comandos.pdf",
    sintaxis: "dig dominio | nslookup dominio",
    desc: "Consulta servidores DNS: traduce dominios a IPs y muestra registros DNS.",
    opciones: ["dig +short : respuesta breve", "MX / TXT / NS : tipos de registro"],
    ejemplos: [{ c: "dig +short ejemplo.com", n: "obtener la IP de un dominio" }, { c: "dig MX ejemplo.com", n: "servidores de correo" }],
    caso: "Fase de reconocimiento (OSINT) autorizado: mapear la infraestructura pública de un dominio objetivo.", aviso: "" },
  { id: "wget", nombre: "wget / curl", cat: "Redes", fuente: "comandos.pdf",
    sintaxis: "wget url | curl [opciones] url",
    desc: "Descargan y transfieren datos por HTTP/HTTPS/FTP. curl es muy flexible para APIs y cabeceras.",
    opciones: ["wget -c : reanuda descargas", "curl -I : solo cabeceras", "curl -X POST : método HTTP", "curl -H : cabecera personalizada"],
    ejemplos: [{ c: "curl -I https://ejemplo.com", n: "ver cabeceras (servidor, tecnología)" }, { c: "wget https://sitio/archivo.zip", n: "descargar un archivo" }],
    caso: "Reconocimiento web: 'curl -I' revela el servidor y tecnologías (banner grabbing básico).", aviso: "" },
  { id: "scp", nombre: "scp / rsync", cat: "Redes", fuente: "comandos.pdf",
    sintaxis: "scp archivo user@host:/ruta | rsync -av origen/ destino/",
    desc: "Copian archivos de forma segura por red (SSH). rsync sincroniza eficientemente (solo cambios).",
    opciones: ["scp -P : puerto", "rsync -a : preserva atributos", "rsync -z : comprime", "rsync --delete : espeja"],
    ejemplos: [{ c: "scp informe.pdf ana@10.0.0.5:/home/ana/", n: "subir un archivo por SSH" }, { c: "rsync -avz web/ ana@10.0.0.5:/var/www/", n: "desplegar un sitio" }],
    caso: "Exfiltrar evidencias del laboratorio o desplegar y respaldar de forma segura.", aviso: "" }
);

/* ---------------- HACKING / PENTESTING (LINUX FOR HACKERS) ----------------
   Herramientas legítimas de seguridad. Úsalas SOLO en entornos
   propios o autorizados (tu laboratorio, TryHackMe, Hack The Box).
   ------------------------------------------------------------------------- */
COMANDOS.push(
  { id: "nmap", nombre: "nmap", cat: "Hacking", fuente: "Linux for Hackers (cap. Kali / herramientas de red)",
    sintaxis: "nmap [tipo] [opciones] objetivo",
    desc: "Escáner de red de referencia: descubre hosts activos, puertos abiertos, servicios y versiones. Automatiza el envío de paquetes que harías a mano.",
    opciones: ["-sT : escaneo TCP connect", "-sV : detecta versión de servicios", "-p : puertos (-p 80,443 o -p-)", "-oG/-oN : guarda salida (grepeable/normal)", "-T4 : velocidad"],
    ejemplos: [{ c: "nmap -sV localhost", n: "servicios y versiones de TU equipo" }, { c: "nmap -sn 192.168.1.0/24", n: "qué dispositivos hay en TU red" }, { c: "nmap -sT 10.0.0.5 -p- -oN scan.txt", n: "todos los puertos de una máquina de laboratorio" }],
    caso: "Fase de escaneo de un pentest autorizado: inventario de puertos/servicios para planificar la enumeración. Como defensor, te dice qué expone tu red.",
    aviso: "Escanear redes o equipos ajenos sin permiso es ILEGAL. Hazlo solo en tu laboratorio o con autorización por escrito." },
  { id: "tcpdump", nombre: "tcpdump", cat: "Hacking", fuente: "Linux for Hackers (herramientas de red)",
    sintaxis: "tcpdump [opciones] [filtro]",
    desc: "Capturador de paquetes clásico por línea de comandos. Filtra por host, red, puerto o protocolo. Base del análisis de tráfico (sniffing).",
    opciones: ["-i : interfaz", "-w archivo.pcap : guarda captura", "-r : lee una captura", "host/port/net : filtros"],
    ejemplos: [{ c: "sudo tcpdump -i any port 80", n: "tráfico HTTP en vivo" }, { c: "sudo tcpdump -w captura.pcap", n: "guardar para analizar luego en Wireshark" }],
    caso: "Blue team: detectar tráfico anómalo o sin cifrar. Red team (lab): entender la comunicación de un servicio.",
    aviso: "Capturar tráfico de redes ajenas sin permiso vulnera la privacidad y la ley. Solo en tu red/lab." },
  { id: "wireshark", nombre: "Wireshark", cat: "Hacking", fuente: "Linux for Hackers (herramientas de red)",
    sintaxis: "wireshark (interfaz gráfica)",
    desc: "Analizador de protocolos con interfaz gráfica: inspecciona paquete a paquete lo capturado, con filtros potentes. Más fácil de dominar que tcpdump.",
    opciones: ["Filtros de visualización: http, tcp.port==443, ip.addr==...", "Follow TCP Stream : reconstruye una conversación"],
    ejemplos: [{ c: "Filtro: http.request", n: "ver todas las peticiones HTTP" }, { c: "Filtro: tcp.port == 22", n: "aislar tráfico SSH" }],
    caso: "Análisis forense y de incidentes: reconstruir qué ocurrió en la red a partir de una captura .pcap.",
    aviso: "Analiza solo capturas de redes propias o autorizadas." },
  { id: "netcat", nombre: "netcat (nc)", cat: "Hacking", fuente: "Linux for Hackers (herramientas de red)",
    sintaxis: "nc [opciones] host puerto",
    desc: "La 'navaja suiza' de redes: abre conexiones TCP/UDP, prueba puertos, transfiere datos y crea conexiones de escucha.",
    opciones: ["-l : modo escucha", "-v : detallado", "-p : puerto", "-z : escaneo sin enviar datos"],
    ejemplos: [{ c: "nc -zv 10.0.0.5 22", n: "comprobar si el puerto 22 está abierto" }, { c: "nc -lvp 4444", n: "ponerse a la escucha en un laboratorio" }],
    caso: "Verificar conectividad y servicios durante una prueba; práctica de conexiones en laboratorios CTF.",
    aviso: "Útil y potente; usado de forma indebida puede crear puertas traseras. Solo en entornos propios/autorizados." },
  { id: "lsof", nombre: "lsof", cat: "Hacking", fuente: "Linux for Hackers (herramientas de red)",
    sintaxis: "lsof [opciones]",
    desc: "Lista los archivos abiertos por el sistema, incluidos sockets de red y qué proceso los usa.",
    opciones: ["-i : conexiones de red", "-p PID : archivos de un proceso", "-i :puerto : quién usa un puerto"],
    ejemplos: [{ c: "sudo lsof -i :80", n: "qué proceso escucha en el puerto 80" }, { c: "lsof -p 1234", n: "archivos abiertos por un proceso" }],
    caso: "Respuesta a incidentes: identificar un proceso sospechoso y a qué se está conectando.", aviso: "" },
  { id: "strace", nombre: "strace", cat: "Hacking", fuente: "Linux for Hackers (herramientas de red)",
    sintaxis: "strace [opciones] comando",
    desc: "Traza las llamadas al sistema (syscalls) que hace un programa: útil para entender o depurar binarios.",
    opciones: ["-p PID : adjuntar a un proceso", "-e trace=network : solo llamadas de red", "-o archivo : guarda la traza"],
    ejemplos: [{ c: "strace -e trace=network curl ejemplo.com", n: "ver las syscalls de red de curl" }],
    caso: "Análisis de malware en laboratorio aislado: observar qué hace un binario sin tener su código.", aviso: "Analiza binarios desconocidos solo en máquinas virtuales aisladas." },
  { id: "burpsuite", nombre: "Burp Suite", cat: "Hacking", fuente: "Linux for Hackers (cap. Burp Suite)",
    sintaxis: "burpsuite (proxy de aplicación web)",
    desc: "Plataforma para pruebas de seguridad de aplicaciones web. Actúa como proxy entre tu navegador y la web para inspeccionar y modificar peticiones.",
    opciones: ["Proxy : intercepta peticiones", "Repeater : reenvía y modifica manualmente", "Intruder : automatiza pruebas (en lab)"],
    ejemplos: [{ c: "Proxy → Intercept", n: "capturar y analizar una petición de login" }, { c: "Repeater", n: "probar cómo responde el servidor a cambios" }],
    caso: "Auditoría web autorizada: detectar vulnerabilidades OWASP (inyección, control de acceso) en TUS aplicaciones o en laboratorios.",
    aviso: "Solo contra aplicaciones propias o con autorización explícita. PortSwigger Web Security Academy es el lugar legal para practicar." },
  { id: "metasploit", nombre: "Metasploit", cat: "Hacking", fuente: "Linux for Hackers",
    sintaxis: "msfconsole (framework)",
    desc: "Framework de pruebas de penetración que reúne módulos para validar vulnerabilidades de forma estructurada. Se usa en entornos de laboratorio controlados.",
    opciones: ["search : buscar módulos", "use : seleccionar módulo", "set : configurar opciones", "(en laboratorio, con objetivos autorizados)"],
    ejemplos: [{ c: "msfconsole", n: "abrir el framework" }, { c: "search type:auxiliary scanner", n: "módulos de escaneo (no destructivos)" }],
    caso: "Practicar metodología en máquinas vulnerables diseñadas para ello (Metasploitable, TryHackMe).",
    aviso: "Pensado para laboratorios y objetivos autorizados. No lo uses contra sistemas reales ajenos: es delito." }
);

/* ---------------- BASH (Manual de Linux Bash.pdf) ---------------- */
COMANDOS.push(
  { id: "echo", nombre: "echo", cat: "Bash", fuente: "Manual de Linux Bash.pdf",
    sintaxis: "echo [texto]",
    desc: "Imprime texto o el valor de variables en la salida estándar. Pieza básica de cualquier script.",
    opciones: ["-n : sin salto de línea final", "-e : interpreta secuencias como \\n"],
    ejemplos: [{ c: "echo \"Hola $USER\"", n: "muestra tu nombre de usuario" }, { c: "echo \"log\" >> registro.txt", n: "añade una línea a un archivo" }],
    caso: "Mostrar mensajes y registrar pasos en scripts de automatización.", aviso: "" },
  { id: "pipe", nombre: "| (tubería)", cat: "Bash", fuente: "Manual de Linux Bash.pdf",
    sintaxis: "comando1 | comando2",
    desc: "Conecta la salida de un comando con la entrada del siguiente. La filosofía Unix: programas pequeños que se combinan.",
    opciones: [],
    ejemplos: [{ c: "ps aux | grep nginx", n: "filtra los procesos de nginx" }, { c: "cat log | grep ERROR | wc -l", n: "cuenta los errores de un log" }],
    caso: "Encadenar herramientas para analizar datos sin programar (esencial para un analista).", aviso: "" },
  { id: "redir", nombre: "> y >> (redirección)", cat: "Bash", fuente: "Manual de Linux Bash.pdf",
    sintaxis: "comando > archivo | comando >> archivo",
    desc: "Redirige la salida a un archivo. '>' sobrescribe; '>>' añade al final. '2>' redirige errores.",
    opciones: ["> : sobrescribe", ">> : añade", "2> : redirige errores", "&> : salida y errores"],
    ejemplos: [{ c: "nmap -sV host > scan.txt", n: "guarda un escaneo" }, { c: "comando 2> errores.log", n: "guarda solo los errores" }],
    caso: "Guardar resultados de pruebas y separar errores para los informes.", aviso: "'>' borra el contenido previo del archivo; usa '>>' si quieres conservarlo." },
  { id: "shebang", nombre: "#!/bin/bash (shebang)", cat: "Bash", fuente: "Manual de Linux Bash.pdf / Linux for Hackers",
    sintaxis: "#!/bin/bash  (primera línea del script)",
    desc: "Indica con qué intérprete ejecutar el script. Sin él, el sistema no sabe que es un script de Bash.",
    opciones: ["chmod +x script.sh : darle permiso de ejecución", "./script.sh : ejecutarlo"],
    ejemplos: [{ c: "#!/bin/bash\\necho \"Escáner iniciado\"", n: "cabecera + primera instrucción" }],
    caso: "Crear scripts reutilizables (ej: un escáner de puertos con nmap automatizado).", aviso: "" }
);
